# Site settings
title: rockndroid
email: npatarino@gmail.com
description: Android Community in Spanish
baseurl: ""
url: "https://rockndroid.dev" # the base hostname & protocol for your site

twitter_username: madg_events
github_username: https://github.com/organizations/ADGevents

# Build settings
markdown: kramdown
